# -*- coding: utf-8 -*-
""". Electricity Bill Calculation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Naj25lkciSoTRtZCFjvvcZryg5DWaJkn
"""

def calculate_electricity_bill(units):
    total_bill = 0

    print("\nElectricity Bill:")

    # Slab 1: 0-100 units at ₹5/unit
    if units > 0:
        slab_units = min(units, 100)
        slab_amount = slab_units * 5
        print(f"0–100 units @ ₹5/unit = ₹{slab_amount}")
        total_bill += slab_amount
        units -= slab_units

    # Slab 2: 101-300 units at ₹7/unit
    if units > 0:
        slab_units = min(units, 200)  # 101 to 300 is 200 units
        slab_amount = slab_units * 7
        print(f"101–300 units @ ₹7/unit = ₹{slab_amount}")
        total_bill += slab_amount
        units -= slab_units

    # Slab 3: 301-500 units at ₹10/unit
    if units > 0:
        slab_units = min(units, 200)  # 301 to 500 is 200 units
        slab_amount = slab_units * 10
        print(f"301–500 units @ ₹10/unit = ₹{slab_amount}")
        total_bill += slab_amount
        units -= slab_units

    # Slab 4: Above 500 units at ₹15/unit
    if units > 0:
        slab_amount = units * 15
        print(f"Above 500 units @ ₹15/unit = ₹{slab_amount}")
        total_bill += slab_amount

    print(f"\nTotal Amount Payable = ₹{total_bill}")

# Taking input from the user
try:
    usage = int(input("Enter electricity usage in kWh: "))
    if usage < 0:
        print("Usage cannot be negative. Please enter a valid number.")
    else:
        calculate_electricity_bill(usage)
except ValueError:
    print("Invalid input. Please enter a numeric value.")

