# -*- coding: utf-8 -*-
"""Bank Transaction Analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16xeCpQQXZW1L9Nni34A_OGkgSc-5N8ip
"""

def bank_transaction_analyzer():
    print("Welcome to the Bank Transaction Analyzer!")
    print("Enter your transactions one by one. Use + for credit, - for debit.")
    print("Type 'done' when you're finished.\n")

    balance = 0
    transactions = []

    while True:
        entry = input("Enter transaction (e.g.0 to -1 ): ").strip()

        if entry.lower() == 'done':
            break
        try:
            amount = int(entry)
            balance += amount
            transactions.append((amount, balance))
            print(f"Transaction recorded: {'Credit' if amount > 0 else 'Debit'} ₹{abs(amount)} -- New Balance: ₹{balance}")
        except ValueError:
            print("Invalid input. Please enter a number with + or - sign.")

    # Final Summary
    print("\n----- Transaction Summary -----")
    for i, (amount, bal) in enumerate(transactions, 1):
        print(f"{i}. {'Credit' if amount > 0 else 'Debit '}: ₹{abs(amount)} → Balance: ₹{bal}")
    print(f"\nFinal Balance: ₹{balance}")

# Run the analyzer
bank_transaction_analyzer()

