# -*- coding: utf-8 -*-
"""budget.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NIa7yvg65tiTYMXNdhCWkcatj309ir8c
"""

def check_order_fulfillment(inventory, customer_order, budget):
    # Sort inventory by price to prioritize cheaper products first
    inventory_sorted = sorted(inventory, key=lambda item: item['price'])

    total_cost = 0
    remaining_order = customer_order.copy()
    fulfilled_items = []

    for product in inventory_sorted:
        product_name = product['name']
        product_price = product['price']
        available_quantity = product['quantity']

        if product_name in remaining_order:
            requested_quantity = remaining_order[product_name]

            quantity_to_fulfill = min(requested_quantity, available_quantity)
            cost = quantity_to_fulfill * product_price

            if total_cost + cost <= budget:
                total_cost += cost
                fulfilled_items.append((product_name, quantity_to_fulfill))
                remaining_order[product_name] -= quantity_to_fulfill

                if remaining_order[product_name] == 0:
                    del remaining_order[product_name]
            else:
                # Try to fulfill part of the request within the remaining budget
                affordable_quantity = (budget - total_cost) // product_price
                if affordable_quantity > 0:
                    partial_cost = affordable_quantity * product_price
                    total_cost += partial_cost
                    fulfilled_items.append((product_name, affordable_quantity))
                    remaining_order[product_name] -= affordable_quantity

                    if remaining_order[product_name] == 0:
                        del remaining_order[product_name]
                break  # Budget reached

    if not remaining_order:
        return "The order can be fully fulfilled within the budget."
    elif len(fulfilled_items) > 0:
        return "The order is partially fulfillable within the budget."
    else:
        return "The order is not fulfillable within the budget."

# Example inventory and customer order
inventory = [
    {'name': 'Laptop', 'quantity': 3, 'price': 1000},
    {'name': 'Mouse', 'quantity': 10, 'price': 50},
    {'name': 'Keyboard', 'quantity': 5, 'price': 150},
    {'name': 'Monitor', 'quantity': 2, 'price': 300}
]

customer_order = {
    'Laptop': 1,
    'Mouse': 2,
    'Keyboard': 1
}

budget = 1300

result = check_order_fulfillment(inventory, customer_order, budget)
print(result)

