# -*- coding: utf-8 -*-
"""Date Difference Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BQEhIwcelCpUlXrJ13YLM6OH3pl4eXFk
"""

from datetime import datetime

def calculate_days_lived():
    print("Welcome! Let's find out how many days you've lived.")

    # Ask the user for their birthdate
    birth_input = input("Enter your birthdate (format: dd-mm-yyyy): ")

    # Ask the user for today's date (or any date they want to compare with)
    today_input = input("Enter today's date (format: dd-mm-yyyy): ")

    # Convert the entered strings into real date objects
    try:
        birth_date = datetime.strptime(birth_input, "%d-%m-%Y")
        today_date = datetime.strptime(today_input, "%d-%m-%Y")

        # Calculate the difference between the two dates
        difference = today_date - birth_date
        days_lived = difference.days

        # Tell the user the result in a friendly way
        if days_lived >= 0:
            print(f"\nYou've lived for {days_lived} days. That's amazing!")
        else:
            print("\nOops! It looks like the birthdate is after today's date. Please check your input.")

    except ValueError:
        print("\nHmm, something's not right. Please make sure both dates are in dd-mm-yyyy format.")

# Run the program
calculate_days_lived()

