# -*- coding: utf-8 -*-
"""Reverse Counting (Recursion Check).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BL33okD5Prrl4AO7klzmsQFyRGqqxnXK
"""

import sys
sys.setrecursionlimit(1100)  # Raise the limit slightly above 1000

def print_down_from(number):
    if number == 0:
        return
    print(number)
    print_down_from(number - 1)

print_down_from(1000)

