# -*- coding: utf-8 -*-
"""seating_arrangement.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NwXmhDVDI5nJAR8b86IJ4j3zGCdV-2-K
"""

from itertools import permutations

def does_everyone_sit_happily(arrangement, preferences):
    num_folks = len(arrangement)
    for i in range(num_folks):
        person = arrangement[i]
        neighbor_to_the_left = arrangement[i - 1]
        neighbor_to_the_right = arrangement[(i + 1) % num_folks]
        likes = preferences[person]
        if neighbor_to_the_left not in likes or neighbor_to_the_right not in likes:
            return False
    return True

def find_a_good_seating_plan(guest_wishes):
    all_the_ways = permutations(list(guest_wishes.keys())) # Let's look at all the possible seating orders

    for seating_order in all_the_ways:
        if does_everyone_sit_happily(seating_order, guest_wishes):
            return list(seating_order) # Found a plan where everyone's happy!

    return "Couldn't find a seating arrangement that makes everyone happy."

the_guests = {
    'Konark': ['Harsh', 'Yash'],
    'Harsh': ['Konark', 'Ravi'],
    'Yash': ['Konark', 'Ravi'],
    'Ravi': ['Harsh', 'Yash']
}

dinner_seating = find_a_good_seating_plan(the_guests)
print(dinner_seating)

