# -*- coding: utf-8 -*-
"""Shortest Path Finder.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cao4IX6_FgarrYqtYggM5y4uRNWq_OaF
"""

def find_shortest_path(city_connections, start_city, destination_city):
    distances = {city: float('inf') for city in city_connections}
    distances[start_city] = 0
    path_so_far = {start_city: [start_city]}
    unvisited = list(city_connections.keys())

    while unvisited:
        current_city = None
        for city in unvisited:
            if current_city is None or distances[city] < distances[current_city]:
                current_city = city
        if current_city is None:
            break
        unvisited.remove(current_city)

        if current_city == destination_city:
            break

        for neighbor, distance in city_connections[current_city].items():
            new_distance = distances[current_city] + distance
            if new_distance < distances[neighbor]:
                distances[neighbor] = new_distance
                path_so_far[neighbor] = path_so_far[current_city] + [neighbor]

    if destination_city not in path_so_far:
        return "No path found", float('inf')

    return " -> ".join(path_so_far[destination_city]), distances[destination_city]

cities = {
     'A': {'B': 5, 'C': 10},
     'B': {'A': 5, 'C': 3, 'D': 9},
     'C': {'A': 10, 'B': 3, 'D': 1},
     'D': {'B': 9, 'C': 1}
 }
start_city = 'A'
destination_city = 'D'
shortest_path, total_distance = find_shortest_path(cities, start_city, destination_city)

print(f"Shortest path from {start_city} to {destination_city}: {shortest_path}")
print(f"Total distance: {total_distance}")

