# -*- coding: utf-8 -*-
"""sort letters .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Smv47FWdlt3BuTB-jwTnO3EgNjDhNcY-
"""

def sort_letters_digits(s):
    letters = sorted([ch for ch in s if ch.isalpha()])
    digits = sorted([ch for ch in s if ch.isdigit()])
    return ''.join(letters + digits)

# Example usage
input_str = "B4A1D3"
result = sort_letters_digits(input_str)
print(f"Output: {result}")

