# -*- coding: utf-8 -*-
"""Task Scheduling Problem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K4atdeqnWlFHNKFGsDFvTDknKlGD62po
"""

def task(tasks):
    sort_task = sort(tasks, key=lambda task: task['deadline'])
    task_count = 0
    current_time = 0
    for task in sort_task:
        deadline = task['deadline']
        duration = task['duration']
        if current_time + duration <= deadline:
            task_count += 1
            current_time += duration
    return task_count

def main():
    task_list = [
        {'name': 'Task 1', 'deadline': 4, 'duration': 2},
        {'name': 'Task 2', 'deadline': 3, 'duration': 1},
        {'name': 'Task 3', 'deadline': 2, 'duration': 1},
        {'name': 'Task 4', 'deadline': 1, 'duration': 2},
    ]
    max_completed = task(task_list)
    print(f"The maximum number of tasks the engineer can complete on time is: {max_completed}")

if __name__ == "__main__":
    main()

