# -*- coding: utf-8 -*-
"""Text_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GE7HkK0a2SVNJjUUOmwFyunClKNw7DZH
"""

import re


irrelevant_words = ['the', 'is', 'at', 'on', 'in', 'and', 'a', 'an', 'to', 'of', 'for', 'with', 'that', 'this', 'it', 'by', 'from']


def count_word_occurrences(text_to_analyze):
    text_to_analyze = text_to_analyze.lower()  # Make sure we're not tripped up by capitalization!
    individual_words = re.findall(r'\b[a-z]+\b', text_to_analyze)  # Extract the words themselves

    word_tally = {}  # Where we'll store the counts

    for the_current_word in individual_words:
        if the_current_word not in irrelevant_words:  # Filter out those common, less-meaningful words
            if the_current_word in word_tally:
                word_tally[the_current_word] += 1  # We've seen this word before, so increase its count.
            else:
                word_tally[the_current_word] = 1  # First time encountering this word; give it a count of 1.

    return word_tally


def get_top_prefixed_words(all_word_counts, starting_pattern, number_to_return):
    matching_words_with_counts = []  # A place to store the matching words and their counts

    for word in all_word_counts:
        if word.startswith(starting_pattern):
            matching_words_with_counts.append((word, all_word_counts[word]))


    matching_words_with_counts.sort(key=lambda pair: pair[1], reverse=True)

    return matching_words_with_counts[:number_to_return]


sample_text = """
Gujarat, a state nestled in the western part of India, is a thriving example of how tradition and modernity can thrive side by side. Through the centuries, this land has witnessed thoughtful transitions, thorough development, and a thrilling journey through time, shaping it into one of the most dynamic regions in the country.

The thriving economy of Gujarat is a testament to its forward-thinking strategies. Thriving textile industries, thermal power plants, and thriving ports along the Arabian Sea have all contributed to the state’s economic strength. Its capital city, Gandhinagar, and the commercial hub, Ahmedabad, reflect a thoughtful blend of heritage and modern infrastructure. The state’s commitment to thorough industrial planning and the thoughtful encouragement of entrepreneurship have led to thriving business communities throughout its cities and towns.

Though steeped in history, Gujarat is not trapped in the past. The thoughtful preservation of ancient architecture, such as the thirteenth-century Sun Temple at Modhera and the UNESCO-listed Rani ki Vav (a stepwell), is a thrilling sight for tourists and historians alike. These structures not only represent artistic excellence but also the theme of sustainability and innovation that has threaded through Gujarati history.

Gujarat is also the land where the thoughts of Mahatma Gandhi took shape. The Sabarmati Ashram in Ahmedabad remains a thorough reminder of his teachings of peace and truth. Visitors are often thrilled to walk the same paths where he once tread, thinking deeply about the philosophies that changed a nation.

The culture of Gujarat is a theater of colors, festivals, and traditions. From the thunderous beats of Dhol during Navratri to the thoughtful expressions in folk theater like Bhavai, the cultural life here is thriving and full of energy. The traditional attire, featuring vibrant themes and threadwork, further adds to the theatrical charm of the state.

Gujarat’s geography is just as thrilling. The white salt desert of the Rann of Kutch is a theme park of nature’s wonders, where thousands of tourists throng during the Rann Utsav, thrilled by the contrast of culture and landscape. The Gir Forest, the only home of the Asiatic lion, represents the state’s thorough commitment to wildlife conservation.

Furthermore, the state’s thoughtful approach to tourism and heritage conservation makes it a thorough favorite among travelers. The Statue of Unity, the world’s tallest statue, stands tall as a thrilling tribute to Sardar Vallabhbhai Patel, a figure who played a thorough role in the unification of India.

Through thick and thin, Gujarat has remained a state that thrives. Its people are thoughtful, its history is thorough, and its vision for the future is thrilling. In every theme of its story—be it trade, tradition, or transformation—Gujarat shines as a thoughtful and thriving example of what a state can become when its past is honored, and its future is thoroughly planned.




"""

word_frequency_report = count_word_occurrences(sample_text)
top_3_words_starting_with_th = get_top_prefixed_words(word_frequency_report, 'th', 3)

print("Top words that begin with 'th':")
for word, frequency in top_3_words_starting_with_th:
    print(f"{word} - {frequency}")

